pragma ComponentBehavior: Bound

import QtQuick
import Quickshell.Io
import qs.services

// Still image for a wallpaper; video thumbnails are generated by the CLI off-thread.
Image {
    id: root

    property string path
    property string generatedThumbnail
    readonly property bool useSaved: Wallpapers.isVideo(path) && path === Wallpapers.actualCurrent

    function refresh(): void {
        thumbnailProcess.running = false;
        generatedThumbnail = "";
        if (Wallpapers.isVideo(path) && !useSaved) {
            thumbnailProcess.requestedPath = path;
            thumbnailProcess.running = true;
        }
    }

    asynchronous: true
    fillMode: Image.PreserveAspectCrop
    retainWhileLoading: true
    cache: false
    source: Wallpapers.isVideo(path) ? (useSaved ? Wallpapers.thumbnailUrl : generatedThumbnail ? Qt.resolvedUrl("file://" + encodeURIComponent(generatedThumbnail).replace(/%2F/gi, "/")) : "") : (path ? Qt.resolvedUrl("file://" + encodeURIComponent(path).replace(/%2F/gi, "/")) : "")

    onPathChanged: refresh()
    onUseSavedChanged: refresh()
    Component.onCompleted: refresh()
    Component.onDestruction: thumbnailProcess.running = false

    Process {
        id: thumbnailProcess

        property string requestedPath

        command: ["caelestia", "wallpaper", "--thumbnail-info", requestedPath]
        stdout: StdioCollector {
            onStreamFinished: {
                if (!text().trim())
                    return;
                const result = JSON.parse(text());
                if (result.source === root.path && !root.useSaved)
                    root.generatedThumbnail = result.thumbnail;
            }
        }
    }
}
